version: '3'
services:
  appliance-stmp:
    image: com.ymagis.emulator/appliance-stmp

    ports:
      - "161:161"
    networks:
      service1_net:
        ipv4_address: 172.22.0.100

networks:
  service1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16